// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: klaussometer

#ifndef _KLAUSSOMETER_UI_H
#define _KLAUSSOMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_Arrows_ADF_big);
LV_FONT_DECLARE( ui_font_Battery);
LV_FONT_DECLARE( ui_font_Battery2);
LV_FONT_DECLARE( ui_font_Epicycles);
LV_FONT_DECLARE( ui_font_Monserrat_Bold_18);
LV_FONT_DECLARE( ui_font_Monserrat_bold_32);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
