// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: klaussometer

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_TempArc1;
extern lv_obj_t *ui_TempArc2;
extern lv_obj_t *ui_TempArc3;
extern lv_obj_t *ui_TempArc4;
extern lv_obj_t *ui_TempLabel1;
extern lv_obj_t *ui_TempLabel2;
extern lv_obj_t *ui_TempLabel3;
extern lv_obj_t *ui_TempLabel4;
extern lv_obj_t *ui_RoomName1;
extern lv_obj_t *ui_RoomName2;
extern lv_obj_t *ui_RoomName3;
extern lv_obj_t *ui_RoomName4;
extern lv_obj_t *ui_StatusMessage;
extern lv_obj_t *ui_HumidLabel1;
extern lv_obj_t *ui_HumidLabel3;
extern lv_obj_t *ui_HumidLabel4;
extern lv_obj_t *ui_HumidLabel2;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_TextRooms;
extern lv_obj_t *ui_TempArcFC;
extern lv_obj_t *ui_TempLabelFC;
extern lv_obj_t *ui_TextForecastName;
extern lv_obj_t *ui_FCConditions;
extern lv_obj_t *ui_FCWindSpeed;
extern lv_obj_t *ui_FCUpdateTime;
extern lv_obj_t *ui_BatteryArc;
extern lv_obj_t *ui_BatteryLabel;
extern lv_obj_t *ui_TextBattery;
extern lv_obj_t *ui_SolarArc;
extern lv_obj_t *ui_SolarLabel;
extern lv_obj_t *ui_TextSolar;
extern lv_obj_t *ui_UsingArc;
extern lv_obj_t *ui_TextUsing;
extern lv_obj_t *ui_UsingLabel;
extern lv_obj_t *ui_ChargingLabel;
extern lv_obj_t *ui_AsofTimeLabel;
extern lv_obj_t *ui_ChargingTime;
extern lv_obj_t *ui_TextKlaussometer;
extern lv_obj_t *ui_WiFiStatus;
extern lv_obj_t *ui_ServerStatus;
extern lv_obj_t *ui_WeatherStatus;
extern lv_obj_t *ui_SolarStatus;
extern lv_obj_t *ui_SolarMinMax;
extern lv_obj_t *ui_GridBought;
extern lv_obj_t *ui_TempArc5;
extern lv_obj_t *ui_TempLabel5;
extern lv_obj_t *ui_RoomName5;
extern lv_obj_t *ui_FCMin;
extern lv_obj_t *ui_FCMax;
extern lv_obj_t *ui_HumidLabel5;
extern lv_obj_t *ui_Direction1;
extern lv_obj_t *ui_Direction2;
extern lv_obj_t *ui_Direction3;
extern lv_obj_t *ui_Direction4;
extern lv_obj_t *ui_Direction5;
extern lv_obj_t *ui_UVArc;
extern lv_obj_t *ui_UVLabel;
extern lv_obj_t *ui_TextUV;
extern lv_obj_t *ui_BatteryLabel5;
extern lv_obj_t *ui_UVUpdateTime;
extern lv_obj_t *ui_BatteryLabel1;
extern lv_obj_t *ui_BatteryLabel2;
extern lv_obj_t *ui_BatteryLabel4;
extern lv_obj_t *ui_BatteryLabel3;
extern lv_obj_t *ui_Version;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

